export const IPC = {
  bootstrapGet: 'bootstrap:get',
  workspaceChoose: 'workspace:choose',
  workspaceOpen: 'workspace:open',
  workspaceSwitch: 'workspace:switch',
  reportsList: 'reports:list',
  reportCreate: 'report:create',
  reportGet: 'report:get',
  reportSave: 'report:save',
  reportRename: 'report:rename',
  reportFavorite: 'report:favorite',
  reportDuplicate: 'report:duplicate',
  reportTrash: 'report:trash',
  reportRestore: 'report:restore',
  reportDelete: 'report:delete',
  reportExport: 'report:export',
  revisionCreate: 'revision:create',
  revisionsList: 'revisions:list',
  revisionRestore: 'revision:restore',
  personasList: 'personas:list',
  personaSave: 'persona:save',
  personaDelete: 'persona:delete',
  sourcesImport: 'sources:import',
  sourcesList: 'sources:list',
  chatsList: 'chats:list',
  chatCreate: 'chat:create',
  chatRename: 'chat:rename',
  chatAiSettings: 'chat:ai-settings',
  chatDelete: 'chat:delete',
  messagesList: 'messages:list',
  codexRefresh: 'codex:refresh',
  codexBrowse: 'codex:browse',
  codexLogin: 'codex:login',
  codexTurn: 'codex:turn',
  codexCancel: 'codex:cancel',
  codexEvent: 'codex:event',
  externalOpen: 'external:open',
  clipboardWrite: 'clipboard:write',
  fileChoose: 'file:choose',
  diagnosticCopy: 'diagnostic:copy',
  appConsent: 'app:consent',
} as const;

export type IpcChannel = (typeof IPC)[keyof typeof IPC];
export const IPC_ALLOWLIST = new Set<string>(Object.values(IPC));
